/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeterTypesRouteImport } from './routes/meter-types'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as ReadingsRouteImport } from './routes/readings'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UnitsRouteImport } from './routes/units'
import { Route as UsersRouteImport } from './routes/users'
import { Route as AdminPaymentRequestsRouteImport } from './routes/admin/payment-requests'
import { Route as InvoicesPrintBatchRouteImport } from './routes/invoices_.print-batch'
import { Route as ShopsIndexRouteImport } from './routes/shops/index'
import { Route as TenantIndexRouteImport } from './routes/tenant/index'
import { Route as TenantInvoicesRouteImport } from './routes/tenant/invoices'
import { Route as TenantLoginRouteImport } from './routes/tenant/login'
import { Route as TenantPaymentsRouteImport } from './routes/tenant/payments'
import { Route as TenantProfileRouteImport } from './routes/tenant/profile'
import { Route as TenantStatementRouteImport } from './routes/tenant/statement'
import { Route as InvoicesInvoiceIdPrintRouteImport } from './routes/invoices_.$invoiceId.print'
import { Route as ReceiptsReceiptIdPrintRouteImport } from './routes/receipts_.$receiptId.print'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeterTypesRoute = MeterTypesRouteImport.update({
  id: '/meter-types',
  path: '/meter-types',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingsRoute = ReadingsRouteImport.update({
  id: '/readings',
  path: '/readings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentRequestsRoute = AdminPaymentRequestsRouteImport.update({
  id: '/admin/payment-requests',
  path: '/admin/payment-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesPrintBatchRoute = InvoicesPrintBatchRouteImport.update({
  id: '/invoices_/print-batch',
  path: '/invoices/print-batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIndexRoute = ShopsIndexRouteImport.update({
  id: '/shops/',
  path: '/shops/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/tenant/',
  path: '/tenant/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantInvoicesRoute = TenantInvoicesRouteImport.update({
  id: '/tenant/invoices',
  path: '/tenant/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantLoginRoute = TenantLoginRouteImport.update({
  id: '/tenant/login',
  path: '/tenant/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantPaymentsRoute = TenantPaymentsRouteImport.update({
  id: '/tenant/payments',
  path: '/tenant/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantProfileRoute = TenantProfileRouteImport.update({
  id: '/tenant/profile',
  path: '/tenant/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantStatementRoute = TenantStatementRouteImport.update({
  id: '/tenant/statement',
  path: '/tenant/statement',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesInvoiceIdPrintRoute = InvoicesInvoiceIdPrintRouteImport.update({
  id: '/invoices_/$invoiceId/print',
  path: '/invoices/$invoiceId/print',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsReceiptIdPrintRoute = ReceiptsReceiptIdPrintRouteImport.update({
  id: '/receipts_/$receiptId/print',
  path: '/receipts/$receiptId/print',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/contracts': typeof ContractsRoute
  '/customers': typeof CustomersRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/meter-types': typeof MeterTypesRoute
  '/permissions': typeof PermissionsRoute
  '/properties': typeof PropertiesRoute
  '/readings': typeof ReadingsRoute
  '/receipts': typeof ReceiptsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/units': typeof UnitsRoute
  '/users': typeof UsersRoute
  '/admin/payment-requests': typeof AdminPaymentRequestsRoute
  '/invoices/print-batch': typeof InvoicesPrintBatchRoute
  '/tenant/invoices': typeof TenantInvoicesRoute
  '/tenant/login': typeof TenantLoginRoute
  '/tenant/payments': typeof TenantPaymentsRoute
  '/tenant/profile': typeof TenantProfileRoute
  '/tenant/statement': typeof TenantStatementRoute
  '/shops/': typeof ShopsIndexRoute
  '/tenant/': typeof TenantIndexRoute
  '/invoices/$invoiceId/print': typeof InvoicesInvoiceIdPrintRoute
  '/receipts/$receiptId/print': typeof ReceiptsReceiptIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/contracts': typeof ContractsRoute
  '/customers': typeof CustomersRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/meter-types': typeof MeterTypesRoute
  '/permissions': typeof PermissionsRoute
  '/properties': typeof PropertiesRoute
  '/readings': typeof ReadingsRoute
  '/receipts': typeof ReceiptsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/units': typeof UnitsRoute
  '/users': typeof UsersRoute
  '/admin/payment-requests': typeof AdminPaymentRequestsRoute
  '/invoices/print-batch': typeof InvoicesPrintBatchRoute
  '/tenant/invoices': typeof TenantInvoicesRoute
  '/tenant/login': typeof TenantLoginRoute
  '/tenant/payments': typeof TenantPaymentsRoute
  '/tenant/profile': typeof TenantProfileRoute
  '/tenant/statement': typeof TenantStatementRoute
  '/shops': typeof ShopsIndexRoute
  '/tenant': typeof TenantIndexRoute
  '/invoices/$invoiceId/print': typeof InvoicesInvoiceIdPrintRoute
  '/receipts/$receiptId/print': typeof ReceiptsReceiptIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/contracts': typeof ContractsRoute
  '/customers': typeof CustomersRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/meter-types': typeof MeterTypesRoute
  '/permissions': typeof PermissionsRoute
  '/properties': typeof PropertiesRoute
  '/readings': typeof ReadingsRoute
  '/receipts': typeof ReceiptsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/units': typeof UnitsRoute
  '/users': typeof UsersRoute
  '/admin/payment-requests': typeof AdminPaymentRequestsRoute
  '/invoices_/print-batch': typeof InvoicesPrintBatchRoute
  '/tenant/invoices': typeof TenantInvoicesRoute
  '/tenant/login': typeof TenantLoginRoute
  '/tenant/payments': typeof TenantPaymentsRoute
  '/tenant/profile': typeof TenantProfileRoute
  '/tenant/statement': typeof TenantStatementRoute
  '/shops/': typeof ShopsIndexRoute
  '/tenant/': typeof TenantIndexRoute
  '/invoices_/$invoiceId/print': typeof InvoicesInvoiceIdPrintRoute
  '/receipts_/$receiptId/print': typeof ReceiptsReceiptIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/contracts'
    | '/customers'
    | '/invoices'
    | '/login'
    | '/meter-types'
    | '/permissions'
    | '/properties'
    | '/readings'
    | '/receipts'
    | '/reports'
    | '/settings'
    | '/units'
    | '/users'
    | '/admin/payment-requests'
    | '/invoices/print-batch'
    | '/tenant/invoices'
    | '/tenant/login'
    | '/tenant/payments'
    | '/tenant/profile'
    | '/tenant/statement'
    | '/shops/'
    | '/tenant/'
    | '/invoices/$invoiceId/print'
    | '/receipts/$receiptId/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/contracts'
    | '/customers'
    | '/invoices'
    | '/login'
    | '/meter-types'
    | '/permissions'
    | '/properties'
    | '/readings'
    | '/receipts'
    | '/reports'
    | '/settings'
    | '/units'
    | '/users'
    | '/admin/payment-requests'
    | '/invoices/print-batch'
    | '/tenant/invoices'
    | '/tenant/login'
    | '/tenant/payments'
    | '/tenant/profile'
    | '/tenant/statement'
    | '/shops'
    | '/tenant'
    | '/invoices/$invoiceId/print'
    | '/receipts/$receiptId/print'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/contracts'
    | '/customers'
    | '/invoices'
    | '/login'
    | '/meter-types'
    | '/permissions'
    | '/properties'
    | '/readings'
    | '/receipts'
    | '/reports'
    | '/settings'
    | '/units'
    | '/users'
    | '/admin/payment-requests'
    | '/invoices_/print-batch'
    | '/tenant/invoices'
    | '/tenant/login'
    | '/tenant/payments'
    | '/tenant/profile'
    | '/tenant/statement'
    | '/shops/'
    | '/tenant/'
    | '/invoices_/$invoiceId/print'
    | '/receipts_/$receiptId/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  ContractsRoute: typeof ContractsRoute
  CustomersRoute: typeof CustomersRoute
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  MeterTypesRoute: typeof MeterTypesRoute
  PermissionsRoute: typeof PermissionsRoute
  PropertiesRoute: typeof PropertiesRoute
  ReadingsRoute: typeof ReadingsRoute
  ReceiptsRoute: typeof ReceiptsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  UnitsRoute: typeof UnitsRoute
  UsersRoute: typeof UsersRoute
  AdminPaymentRequestsRoute: typeof AdminPaymentRequestsRoute
  InvoicesPrintBatchRoute: typeof InvoicesPrintBatchRoute
  TenantInvoicesRoute: typeof TenantInvoicesRoute
  TenantLoginRoute: typeof TenantLoginRoute
  TenantPaymentsRoute: typeof TenantPaymentsRoute
  TenantProfileRoute: typeof TenantProfileRoute
  TenantStatementRoute: typeof TenantStatementRoute
  ShopsIndexRoute: typeof ShopsIndexRoute
  TenantIndexRoute: typeof TenantIndexRoute
  InvoicesInvoiceIdPrintRoute: typeof InvoicesInvoiceIdPrintRoute
  ReceiptsReceiptIdPrintRoute: typeof ReceiptsReceiptIdPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meter-types': {
      id: '/meter-types'
      path: '/meter-types'
      fullPath: '/meter-types'
      preLoaderRoute: typeof MeterTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readings': {
      id: '/readings'
      path: '/readings'
      fullPath: '/readings'
      preLoaderRoute: typeof ReadingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payment-requests': {
      id: '/admin/payment-requests'
      path: '/admin/payment-requests'
      fullPath: '/admin/payment-requests'
      preLoaderRoute: typeof AdminPaymentRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices_/print-batch': {
      id: '/invoices_/print-batch'
      path: '/invoices/print-batch'
      fullPath: '/invoices/print-batch'
      preLoaderRoute: typeof InvoicesPrintBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/': {
      id: '/shops/'
      path: '/shops'
      fullPath: '/shops/'
      preLoaderRoute: typeof ShopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/': {
      id: '/tenant/'
      path: '/tenant'
      fullPath: '/tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/invoices': {
      id: '/tenant/invoices'
      path: '/tenant/invoices'
      fullPath: '/tenant/invoices'
      preLoaderRoute: typeof TenantInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/login': {
      id: '/tenant/login'
      path: '/tenant/login'
      fullPath: '/tenant/login'
      preLoaderRoute: typeof TenantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/payments': {
      id: '/tenant/payments'
      path: '/tenant/payments'
      fullPath: '/tenant/payments'
      preLoaderRoute: typeof TenantPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/profile': {
      id: '/tenant/profile'
      path: '/tenant/profile'
      fullPath: '/tenant/profile'
      preLoaderRoute: typeof TenantProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/statement': {
      id: '/tenant/statement'
      path: '/tenant/statement'
      fullPath: '/tenant/statement'
      preLoaderRoute: typeof TenantStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices_/$invoiceId/print': {
      id: '/invoices_/$invoiceId/print'
      path: '/invoices/$invoiceId/print'
      fullPath: '/invoices/$invoiceId/print'
      preLoaderRoute: typeof InvoicesInvoiceIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts_/$receiptId/print': {
      id: '/receipts_/$receiptId/print'
      path: '/receipts/$receiptId/print'
      fullPath: '/receipts/$receiptId/print'
      preLoaderRoute: typeof ReceiptsReceiptIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  ContractsRoute: ContractsRoute,
  CustomersRoute: CustomersRoute,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  MeterTypesRoute: MeterTypesRoute,
  PermissionsRoute: PermissionsRoute,
  PropertiesRoute: PropertiesRoute,
  ReadingsRoute: ReadingsRoute,
  ReceiptsRoute: ReceiptsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  UnitsRoute: UnitsRoute,
  UsersRoute: UsersRoute,
  AdminPaymentRequestsRoute: AdminPaymentRequestsRoute,
  InvoicesPrintBatchRoute: InvoicesPrintBatchRoute,
  TenantInvoicesRoute: TenantInvoicesRoute,
  TenantLoginRoute: TenantLoginRoute,
  TenantPaymentsRoute: TenantPaymentsRoute,
  TenantProfileRoute: TenantProfileRoute,
  TenantStatementRoute: TenantStatementRoute,
  ShopsIndexRoute: ShopsIndexRoute,
  TenantIndexRoute: TenantIndexRoute,
  InvoicesInvoiceIdPrintRoute: InvoicesInvoiceIdPrintRoute,
  ReceiptsReceiptIdPrintRoute: ReceiptsReceiptIdPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
